In [1]:
import json
import pandas as pd
data = pd.read_csv(r'data.csv')
d_to_json = {}

def promedio(location):
    prom = list(data.loc[data['location'] == location][['temperature','pressure']].mean())
    return float('{0:.1f}'.format(prom[0])), float('{0:.1f}'.format(prom[1]))

locs = sorted(list(data['location'].unique()))
for location in locs:
    d_to_json[str(location)] = promedio(location)

with open('promedios.json', 'w') as f:
    json.dump(d_to_json, f)

data_nuevo = data
data_nuevo['above_avg_temp'] = data_nuevo.apply(
    lambda n: 'SI' if n.temperature > d_to_json[str(n.location)][0] else 'NO'
    if n.temperature < d_to_json[str(n.location)][0] else 'IGUAL',
    axis=1)
data_nuevo['above_avg_pres'] = data_nuevo.apply(
    lambda n: 'SI' if n.pressure > d_to_json[str(n.location)][1] else 'NO'
    if n.pressure < d_to_json[str(n.location)][1] else 'IGUAL',
    axis=1)
print(data_nuevo)

data_nuevo.to_csv(r'data_nuevo.csv', index=False)

       id  location  temperature  pressure above_avg_temp above_avg_pres
0       1         2           64         1             SI             NO
1       2         4           20        77             NO             SI
2       3         5           70        21             SI             NO
3       4         1           67         5             SI             NO
4       5         2           67        87             SI             SI
..    ...       ...          ...       ...            ...            ...
995   996         3           67        61             SI             SI
996   997         3           47        27             SI             NO
997   998         3           69       100             SI             SI
998   999         1           61        44             SI             NO
999  1000         1           41        31             NO             NO

[1000 rows x 6 columns]